### ISSUE TITLE
Add a bot approval workflow

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/upx#9]
In some of our Paketo Buildpacks that consume automation from https://github.com/paketo-buildpacks/github-config, we have implemented a workflow to [auto-approve](https://github.com/paketo-buildpacks/github-config/blob/main/implementation/.github/workflows/approve-bot-pr.yml) and [auto-merge](https://github.com/paketo-buildpacks/github-config/blob/main/implementation/.github/workflows/auto-merge.yml) our PRs opened by bots (Dependabot / Paketo Bot). This reduces overhead for maintainers, since our tests should catch any errors that get introduced.

It would be great if the UPX buildpack, and others in the Utilities grouping had this automation. It may be even better to create automation for these buildpacks in paketo-buildpacks/github-config so we can reduce the number of places we have to make changes.

@dmikusa-pivotal is there any reason against doing this?

**Comment by dmikusa-pivotal** [comment]
To this point, the Java buildpacks team has taken the approach of not auto approving anything. Instead, we have a tool that we use to bulk merge PRs across repos. It's similar but it allows us to have a human review/confirm before merging anything.

What types of PRs would this merge automatically? Do you have specific examples? Also, what's required for this to work? I'm guessing we'll need an added workflow, which requires changes to pipeline-builder. Is there anything else we'd need to change? Do we need to modify project permissions? 

Thanks

**Comment by sophiewigmore** [comment]
@dmikusa-pivotal I wasn't aware of this tool, I can check it out. It might be helpful for the @paketo-buildpacks/utilities-maintainers to familiarize themselves with it.

Our automation auto approves any PRs that are opened by Paketo Bot or Dependabot and also pass a set of tests. For example, in our implementation buildpacks the [`approve-bot-pr.yml`](https://github.com/paketo-buildpacks/github-config/blob/7f0e3f54cb4a363378e50de74cb7b1cf70e6bcc4/implementation/.github/workflows/approve-bot-pr.yml) runs whenever a workflow called "Test Pull Request" successfully completes. It downloads the PR payload (we uploaded it during Test Pull Request), and then check the author, commit verification, and if any human committers added onto the PR. If all the conditions are met, we approve the PR. We also have the [`auto-merge`](https://github.com/paketo-buildpacks/github-config/blob/7f0e3f54cb4a363378e50de74cb7b1cf70e6bcc4/implementation/.github/workflows/auto-merge.yml) workflow, which runs once there is a PR review, and will just merge in the PR.

You can see an example of what this looks like in the checks associated with [this PR](https://github.com/paketo-buildpacks/node-engine/pull/341), and it's associated [bot approval workflow](https://github.com/paketo-buildpacks/node-engine/runs/3264031737?check_suite_focus=true).

I guess what will be required here is that we will need to add the related workflows. I'm not aware of the pipeline builder, so I'm not sure what else would need to happen.

**Comment by sophiewigmore** [comment]
In general, all of our non-java implementation buildpacks and language family buildpacks share a common set of workflows and actions defined in github-config. Since the Java buildpacks do something separate, it might not be worthwhile to move all of these buildpacks over to a different standard. When I filed this issue, I wasn't aware of the tool you mentioned and was looking for a way to reduce overhead for maintainers/make it a more cohesive experience with the other buildpacks we maintain.

**Comment by dmikusa-pivotal** [comment]
>@dmikusa-pivotal I wasn't aware of this tool, I can check it out. It might be helpful for the

I can demo the tool, if it would be helpful. I put this tool together when I started working on buildpacks cause previously we were merging things manually, which was time-consuming. Feedback on the instructions/tools would be welcome.

>You can see an example of what this looks like in the checks associated with this PR, and it's associated bot approval workflow.

One thing that worries me about auto-merge capabilities is that we don't have the same test design. There are no integration tests, where you'd actually `pack build` something, with any of the Java/utilities buildpacks. Instead, we have taken the approach of leaning on our unit tests as much as possible. We make use of mocks to test some integration scenarios and we do the occasional bit of manual integration testing (depending on what is being changed/merged). The net benefit is that our tests are lightweight and run very quickly. The downside is that there's occasionally some manual testing required, which gives me concern with auto merging PRs.

>I'm not aware of the pipeline builder, so I'm not sure what else would need to happen.

All of the workflows for Java/Utilities buildpacks are auto-generated by the pipeline-builder. There's an update-pipeline.yml workflow that runs and will submit PRs that keep everything in sync. To make a change to a workflow, you have to update the pipeline-builder. Then all of the buildpacks will pick up the change automatically (they'll get PRs submitted). What we'd have to be careful of is that if you try to change stuff manually, you end up in a fight with [pipeline-builder](https://github.com/paketo-buildpacks/pipeline-builder) where it tries to overwrite your changes. If we did want to go forward with changes, we'd probably want to PR those into pipeline-builder.

>In general, all of our non-Java implementation buildpacks and language family buildpacks share a common set of workflows and actions defined in github-config. Since the Java buildpacks do something separate, it might not be worthwhile to move all of these buildpacks over to a different standard.

I think my vote would be to hold off on auto merging. The tool we have for batch merging makes things pretty quick, so while auto-merging stuff would be faster, I think there would be less of a time savings than if we were going from manual merge to auto-merging. Plus there are the concerns above, regarding manual testing that we'd need to address or at least workaround (like my auto merging a smaller subset of PRs).

I'm open to other opinions though. If someone feels strongly and wants to put in the work to add in auto-merging.

**Comment by sophiewigmore** [comment]
@dmikusa-pivotal your concerns are valid here, I was missing some context around the Java/Utilities buildpacks testing strategy, as well as the pipeline-builder information that you shared. I think I agree at this point that we should hold off as well, it just doesn't make sense to shoehorn these buildpacks into that pattern when it doesn't really fit. I would love to get a demo of that tool at some point, I will set up some time! Closing this issue out for now.
